In [17]:
import numpy as np
N = 10
array1 = np.arange(0, N)[::-1]
print(array1)

[9 8 7 6 5 4 3 2 1 0]


In [18]:
# задание не понятно
N = 81
var1 = np.arange(0, N)[::-1]
diag_mat1 = var1.reshape(int(np.sqrt(N)),int(np.sqrt(N)))
#np.diagonal(diag_mat1)
print(np.diag(diag_mat1).sum())
diag_mat1

360


array([[80, 79, 78, 77, 76, 75, 74, 73, 72],
       [71, 70, 69, 68, 67, 66, 65, 64, 63],
       [62, 61, 60, 59, 58, 57, 56, 55, 54],
       [53, 52, 51, 50, 49, 48, 47, 46, 45],
       [44, 43, 42, 41, 40, 39, 38, 37, 36],
       [35, 34, 33, 32, 31, 30, 29, 28, 27],
       [26, 25, 24, 23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12, 11, 10,  9],
       [ 8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [19]:
# либо так
N = 36
print(np.arange(0, N)[::-1].sum())
np.diag(np.arange(0, N)[::-1])



630


array([[35,  0,  0, ...,  0,  0,  0],
       [ 0, 34,  0, ...,  0,  0,  0],
       [ 0,  0, 33, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  2,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [20]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [22]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [23]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [24]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [26]:
res = [cosine(users_stats[i], next_user_stats)for i in range(len(users_stats))]
val4 = min(res, key=lambda x: (abs(x - 1), x))
for i in enumerate(res):
    if val4 == i[1]:
        print(users_stats[i[0]], '\n' , i[0]+1)

[0 1 1 0 0 0] 
 8
